name: Create Release on Push Tag
on:
 push:
   tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update release
        uses: actions/github-script@2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const fs = require('fs');
              const path = require('path');
              var json;
              var html = "";
              try {
                json = JSON.parse(fs.readFileSync);
                for(const coin in json){
                  html += "<h1>"+coin+</h1>;
                  html += "wallet: "+json[coin].wallet+<br>;
                  html += "scan: "+json[coin].scan+<br>;
                }
              } catch (err){
                
              }
              const repo = context.repo.repo;
              const owner = context.repo.owner;
              const tag = process.env.GITHUB_REF_NAME;
              const release= await github.repos.createRelease({
                owner,
                repo,
                tag_name: tag,
                body: html,
                prerelease: false
              });
